export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_SUCCESS = 'AJAX_SUCCESS';
export const GET_LOCATION = 'GET_LOCATION';
export const INIT_MAP_OBJECT = 'INIT_MAP_OBJECT';
export const LOAD_MAP_SUCCESS = 'LOAD_MAP_SUCCESS';
export const CLEAR_MAP_MARKER_BY_LOCATION = "CLEAR_MAP_MARKER_BY_LOCATION";
export const SHOULD_CLEAR_ALL_STOP_SOLVER_MAP_ELEMENTS = "SHOULD_CLEAR_ALL_STOP_SOLVER_MAP_ELEMENTS";

// Search Actions
export const CANCEL_GETTING_GOOGLE_SEARCH_RESULTS = 'CANCEL_GETTING_GOOGLE_SEARCH_RESULTS';
export const GETTING_GOOGLE_SEARCH_RESULTS = 'GETTING_GOOGLE_SEARCH_RESULTS';
export const GETTING_ACTIVE_SEARCH_RESULTS = 'GETTING_ACTIVE_SEARCH_RESULTS';
export const FINISHED_GETTING_GOOGLE_SEARCH_RESULTS = 'FINISHED_GETTING_GOOGLE_SEARCH_RESULTS';
export const GET_GOOGLE_SEARCH_RESULTS_SUCCESS = 'GET_GOOGLE_SEARCH_RESULTS_SUCCESS';
export const GET_ACTIVE_SEARCH_RESULTS_SUCCESS = 'GET_ACTIVE_SEARCH_RESULTS_SUCCESS';
export const GET_ACTIVE_SEARCH_RESULTS_FAIL = 'GET_ACTIVE_SEARCH_RESULTS_FAIL';
export const GET_ACTIVE_CAMPGROUND_DETAILS_SUCCESS = 'GET_ACTIVE_CAMPGROUND_DETAILS_SUCCESS';
export const GET_ACTIVE_CAMPGROUND_DETAILS_FAIL = 'GET_ACTIVE_CAMPGROUND_DETAILS_FAIL';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULT_BY_LOCATION = "CLEAR_SEARCH_RESULT_BY_LOCATION";
export const SET_PLACES_SERVICE = 'SET_PLACES_SERVICE';
export const LOAD_MAP_MARKERS = 'LOAD_MAP_MARKERS';
export const CLEAR_MAP_MARKERS = 'CLEAR_MAP_MARKERS';

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const UPDATE_SELECTED_SEARCH_FILTER = 'UPDATE_SELECTED_SEARCH_FILTER';

// Trips Actions
export const CLEARED_SELECTED_TRIP = 'CLEARED_SELECTED_TRIP';
export const CREATE_NEW_TRIP_DIALOG_OPENED = 'CREATE_NEW_TRIP_DIALOG_OPENED';
export const CREATE_NEW_TRIP_DIALOG_CLOSED = 'CREATE_NEW_TRIP_DIALOG_CLOSED';
export const LOADED_TRIP_SUCCESSFULLY = 'LOADED_TRIP_SUCCESSFULLY';
export const LOADED_TRIPS_SUCCESSFULLY = 'LOADED_TRIPS_SUCCESSFULLY';
export const CREATE_NEW_TRIP = 'CREATE_NEW_TRIP';
export const TRIPS_CHILD_ADDED_SUCCESSFULLY = 'TRIPS_CHILD_ADDED_SUCCESSFULLY';
export const TRIPS_CHILD_CHANGED = 'TRIPS_CHILD_CHANGED';
export const TRIP_DELETED_SUCCESSFULLY = 'TRIP_DELETED_SUCCESSFULLY';
export const ALERT_TRIP_DELETED_SUCCESSFULLY = 'ALERT_TRIP_DELETED_SUCCESSFULLY';
export const CLEAR_ALERT_TRIP_DELETED = 'CLEAR_ALERT_TRIP_DELETED';
export const TRIP_UNDO_DELETE = 'TRIP_UNDO_DELETE';
export const UPDATE_TRIP_NO_OF_STOPS = 'UPDATE_TRIP_NO_OF_STOPS';
export const SELECTED_TRIP_IS_LOADED = 'SELECTED_TRIP_IS_LOADED';
export const SHOW_SELECTED_TRIP = 'SHOW_SELECTED_TRIP';
export const HIDE_SELECTED_TRIP = 'HIDE_SELECTED_TRIP';
export const LOAD_CREATED_EDIT_TRIP_DIALOG = 'LOAD_CREATED_EDIT_TRIP_DIALOG';
export const CLEAR_CREATED_EDIT_TRIP_DIALOG = 'CLEAR_CREATED_EDIT_TRIP_DIALOG';
export const CLEAR_TRIPS = 'CLEAR_TRIPS';

// Trip Stops Actions
export const ADD_TRIP_STOP = 'ADD_TRIP_STOP';
export const TRIP_STOP_ADDED_SUCCESSFULLY = 'TRIP_STOP_ADDED_SUCCESSFULLY';
export const CLEAR_TRIP_STOPS = 'CLEAR_TRIP_STOPS';
export const TRIP_STOP_CHANGED = 'TRIP_STOP_CHANGED';
export const CLEAR_ALL_TRIP_STOP_MAP_MARKERS = 'CLEAR_ALL_TRIP_STOP_MAP_MARKERS';
export const LOAD_ALL_TRIP_STOP_MAP_MARKERS = 'LOAD_ALL_TRIP_STOP_MAP_MARKERS';
export const ADD_ARRAY_OF_TRIP_STOP_MAP_MARKERS = 'ADD_ARRAY_OF_TRIP_STOP_MAP_MARKERS';
export const CLEAR_ARRAY_OF_TRIP_STOP_MAP_MARKERS = 'CLEAR_ARRAY_OF_TRIP_STOP_MAP_MARKERS';
export const CLEAR_TRIP_STOP_SUMMARIES = 'CLEAR_TRIP_STOP_SUMMARIES';
export const LOAD_ALL_TRIP_STOP_SUMMARIES = 'LOAD_ALL_TRIP_STOP_SUMMARIES';
export const UPDATE_MAP_MARKERS = 'UPDATE_MAP_MARKERS';

// Trip Stop Details
export const ADD_TRIP_STOP_DETAILS = 'ADD_TRIP_STOP_DETAILS';

// Trip Stop POIs Actions
export const LOADED_TRIP_STOP_POIS_SUCCESSFULLY = 'LOADED_TRIP_STOP_POIS_SUCCESSFULLY';
export const CLEAR_TRIP_STOP_POIS = 'CLEAR_TRIP_STOP_POIS';
export const TRIP_STOP_POI_REMOVED = 'TRIP_STOP_POI_REMOVED';
export const ADDED_TRIP_STOP_POI_SUCCESSFULLY = 'ADDED_TRIP_STOP_POI_SUCCESSFULLY';
export const REMOVED_TRIP_STOP_POI_SUCCESSFULLY = 'REMOVED_TRIP_STOP_POI_SUCCESSFULLY';
export const REMOVED_ARRAY_OF_TRIP_STOP_POIS_SUCCESSFULLY = 'REMOVED_ARRAY_OF_TRIP_STOP_POIS_SUCCESSFULLY';
export const LOAD_TRIP_STOP_POI_MARKERS = "LOAD_TRIP_STOP_POI_MARKERS";
export const CLEAR_ALL_TRIP_STOP_POI_MAP_MARKERS = "CLEAR_ALL_TRIP_STOP_POI_MAP_MARKERS";
export const CLEAR_TRIP_STOP_POI_MAP_MARKERS_WITH_ARRAY_OF_TRIP_STOP_POIS = "CLEAR_TRIP_STOP_POI_MAP_MARKERS_WITH_ARRAY_OF_TRIP_STOP_POIS";
export const UPDATE_STORE_AFTER_NEW_POI_FROM_TRIP_STOP = "UPDATE_STORE_AFTER_NEW_POI_FROM_TRIP_STOP";
export const REMOVE_TRIP_STOP_POIS_FROM_STORE = "REMOVE_TRIP_STOP_POIS_FROM_STORE";

// Stop Solver Actions
export const LOAD_STOP_SOLVER_CONFIG = 'LOAD_STOP_SOLVER_CONFIG';
export const LOAD_STOP_SOLVER_CONFIG_STOPS = 'LOAD_STOP_SOLVER_CONFIG_STOPS';
export const UPDATED_STOP_SOLVER_CONFIG_VISIBILITY = 'UPDATED_STOP_SOLVER_CONFIG_VISIBILITY';
export const SET_FOCUSED_STOP_SOLVER_MARKER = 'SET_FOCUSED_STOP_SOLVER_MARKER';
export const CLEAR_FOCUSED_STOP_SOLVER_MARKER = 'CLEAR_FOCUSED_STOP_SOLVER_MARKER';
export const UPDATE_SEARCH_RADIUS_FOCUSED_STOP_SOLVER_MARKER = 'UPDATE_SEARCH_RADIUS_FOCUSED_STOP_SOLVER_MARKER';
export const SHOULD_HIDE_FOCUSED_STOP_SOLVER_MARKERS_ELEMENTS = 'SHOULD_HIDE_FOCUSED_STOP_SOLVER_MARKERS_ELEMENTS';
export const UPDATE_STOP_SOLVER_CONFIG_SEARCH_RADIUS = 'UPDATE_STOP_SOLVER_CONFIG_SEARCH_RADIUS';
export const CLEAR_STOP_SOLVER_CONFIG = 'CLEAR_STOP_SOLVER_CONFIG';
export const SET_STOP_SOLVER_CONFIG_IS_REVISING_FALSE = 'SET_STOP_SOLVER_CONFIG_IS_REVISING_FALSE';

// Snackbar Actions
export const LOAD_SNACKBAR = 'LOAD_SNACKBAR';
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';

// Confirm Dialog Actions
export const LOAD_CONFIRM_DIALOG = 'LOAD_CONFIRM_DIALOG';
export const CLEAR_CONFIRM_DIALOG = 'CLEAR_CONFIRM_DIALOG';

// Thinking Actions
export const APP_IS_THINKING = 'APP_IS_THINKING';
export const APP_IS_NOT_THINKING = 'APP_IS_NOT_THINKING';
export const APP_IS_LOADED = 'APP_IS_LOADED';

// Re-Order Trip Stops Dialog Actions
export const LOAD_RE_ORDER_TRIP_STOPS_DIALOG = 'LOAD_RE_ORDER_TRIP_STOPS_DIALOG';
export const CLEAR_RE_ORDER_TRIP_STOPS_DIALOG = 'CLEAR_RE_ORDER_TRIP_STOPS_DIALOG';

// Duplicate Trip Dialog Actions
export const LOAD_DUPLICATE_TRIP_DIALOG = 'LOAD_DUPLICATE_TRIP_DIALOG';
export const CLEAR_DUPLICATE_TRIP_DIALOG = 'CLEAR_DUPLICATE_TRIP_DIALOG';

// User Actions
export const LOADED_USER_FROM_FB = 'LOADED_USER_FROM_FB';
export const CLEAR_USER_FROM_FB = 'CLEAR_USER_FROM_FB';

// Account Actions
export const LOAD_ACCOUNT_DIALOG = 'LOAD_ACCOUNT_DIALOG';
export const CLEAR_ACCOUNT_DIALOG = 'CLEAR_ACCOUNT_DIALOG';

// Settings Actions
export const LOAD_SETTINGS_DIALOG = 'LOAD_SETTINGS_DIALOG';
export const CLEAR_SETTINGS_DIALOG = 'CLEAR_SETTINGS_DIALOG';

// Billing Actions
export const LOAD_BILLING_DIALOG = 'LOAD_BILLING_DIALOG';
export const CLEAR_BILLING_DIALOG = 'CLEAR_BILLING_DIALOG';

// Current User Actions
export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const UPDATE_WANDERS_FIRSTLASTUSERNAME_IN_STORE = 'UPDATE_WANDERS_FIRSTLASTUSERNAME_IN_STORE';
export const UPDATE_WANDERS_DEFAULT_LOCATION = 'UPDATE_WANDERS_DEFAULT_LOCATION';
export const UPDATE_USER_WITH_LAST_TRIP_OPENED = 'UPDATE_USER_WITH_LAST_TRIP_OPENED';

// Directions Dialog Actions
export const LOAD_DIRECTIONS_DIALOG = "LOAD_DIRECTIONS_DIALOG";
export const CLEAR_DIRECTIONS_DIALOG = "CLEAR_DIRECTIONS_DIALOG";

// Send Directions To Dialog Actions
export const LOAD_SEND_DIRECTIONS_TO_DIALOG = "LOAD_SEND_DIRECTIONS_TO_DIALOG";
export const CLEAR_SEND_DIRECTIONS_TO_DIALOG = "CLEAR_SEND_DIRECTIONS_TO_DIALOG";

// Revise Trip Stops Dialog Actions
export const LOAD_REVISE_TRIP_STOPS_DIALOG = "LOAD_REVISE_TRIP_STOPS_DIALOG";
export const CLEAR_REVISE_TRIP_STOPS_DIALOG = "CLEAR_REVISE_TRIP_STOPS_DIALOG";

// Navigation Actions
export const SET_CAN_TRACK_LOCATION = "SET_CAN_TRACK_LOCATION";
export const SET_CURRENT_POSITION = "SET_CURRENT_POSITION";